-- Tabla Customers
CREATE TABLE CUSTOMERS(
    EMAIL varchar(255) PRIMARY KEY,
    NAME varchar(255) NOT NULL,
    VIP_STATUS BOOLEAN NOT NULL DEFAULT false
);

-- Tabla Tickets
CREATE TABLE TICKETS(
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    "TIMESTAMP" TIMESTAMP DEFAULT NOW(),
    CUSTOMER_EMAIL varchar(255) NOT NULL,
    SUMMARY varchar(255),
    CATEGORY varchar(100) NOT NULL,
    URGENCY varchar(20) NOT NULL,
    STATUS varchar(40) NOT NULL,
    N8N_RUN_URL varchar(255),

    FOREIGN KEY(CUSTOMER_EMAIL) REFERENCES CUSTOMERS(EMAIL)
);